blog/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    username = db.Column(db.String(150), unique=True)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    posts = db.relationship('Post', backref='user', passive_deletes=True)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)

blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '3d8167986635e347263c13dc4a498839'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)


    from .views import views
    from .auth import auth
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')



    from .models import User, Post
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

#get user from database
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


#create database
def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

blog/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)




@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template('Login.html', user=current_user)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        #check if email already exists
        user_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if user_exists:
            flash('Email already exists', category='error')
        elif username_exists:
            flash('Username already exists', category='error')
        elif password1 != password2:
            flash("Passwords don't match", category='error')
        elif len(username) < 4:
            flash('Username must be at least 4 characters', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters', category='error')
        elif len(email) < 4:
            flash('Email is invalid', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('register.html', user=current_user)


@auth.route('/Logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

blog/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User
from . import db

views = Blueprint('views', __name__)


@views.route('/')
@views.route('/home')
def home():
    posts = Post.query.all()
    return render_template('home.html', user=current_user, posts=posts)


@views.route('/about')
def about():
    return render_template('about.html')


@views.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        flash('Message sent', category='success')
        return redirect(url_for('views.home'))
    return render_template('contact.html')


@views.route('/creatPosts', methods=['GET', 'POST'])
@login_required
def createPosts():
    if request.method == 'POST':
        content = request.form.get('content')
        if not content:
            flash('Post is empty!', category='error')
        else:
            post = Post(content=content, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('views.home'))
            
    return render_template('createPost.html', name=current_user.username)

@views.route('/delete/<id>')
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    if not post:
        flash('Post does not exist', category='error')
    elif current_user.id != post.id:
        flash('You do not have permission to delete this post', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted!', category='success')
    return redirect(url_for('views.home'))

@views.route('/edit/<id>', methods=['GET', 'POST'])
def edit_post(id):
    post = Post.query.get(id)
    if not post:
        flash('Post does not exist', category='error')
    elif current_user.id != post.id:
        flash('You do not have permission to edit this post', category='error')
    else:
        if request.method == 'POST':
            post.content = request.form.get('content')
            if not post.content:
                flash('Post is empty!', category='error')
            else:
                db.session.add(post)
                db.session.commit()
                flash('Post edited!', category='success')
                return redirect(url_for('views.home'))
    post.content = post.content
    return render_template('edit.html', post=post)


@views.route('/post/<username>')
@login_required
def post(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('User does not exist', category='error')
        redirect(url_for('views.home'))
    else:
        posts = Post.query.filter_by(author=user.id).all()
        return render_template('post.html', posts=posts, username=username, user=current_user)

@views.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@views.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

blog/templates/about.html
{% extends 'base.html' %}

{% block section %}
<div class="container">
  <div class="d-sm-auto">
    <h1>Welcome to <span class="text-warning"> Frank's Blog</span> </h1>
    <h3>A blog to find interesting articles about <span class="text-warning">wildlife</span>, 
      <span class="text-warning"> climate change</span> and <span class="text-warning">community building</span></h3>
  </div>
</div>
{% endblock %}

{% block content %}
<div align="center">
  <div class="container">
    <h1>About Me</h1>
    <article>
      I am a wildlife enthusiast and a community builder. I love to write about wildlife and climate change. 
      I am also a software developer and I love to build web applications. 
      I am currently working on a project to build a community for wildlife enthusiasts. 
      I am a student of AltSchoolAfrica learning backened development aspect of software engineering.
      I am also working on a project to build a web application to help people find the best places to visit in the world.
    </article>
  </div>
    <div class="container">
      <h1>Article Focus</h1>
      <article>
       This blog focuses on wildlife, climate change and community building. In this blog, I will be writing about the following topics:
       wildlife, climate change, community building, leadership and self development, you too will be able to write articles about these topics.
       Thanks for visiting my blog.
      </article>
    </div>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Frank Blog App</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" type="text/css" href="../static/style.css"> -->
    <!-- <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet"> -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
      <div class="container">
        <a class="navbar-brand" href="#"
          >Frank <span class="text-warning">Blog App</span></a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.home')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.about')}}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.contact')}}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.createPosts')}}">Create Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.home')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.about')}}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.contact')}}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <section class="bg-dark text-light p-3 text-center">
      {% block section %} {% endblock %}
    </section>
    {% with messages = get_flashed_messages(with_categories=True) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    "error" %}
    <div class="alert alert-danger alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <main>{% block content %} {% endblock %}</main>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1 >Contact Me</h1>
<form class="col g-3" method="POST">
  <div class="col-md-6">
    <label class="visually-hidden" for="username">Username</label>
    <div class="input-group">
      <div class="input-group-text">@</div>
      <input type="text" class="form-control" id="username" placeholder="Username" name="username" required>
    </div>
    <div class="col-md-6">
      <label for="email" class="form-label">Email</label>
      <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <textarea name="content" id="content" class="form-control mt-2" cols="50" rows="10">  
    </textarea>
    <div class="col-md-12 mt-2" align="center">
      <button type="submit" class="btn btn-dark">Submit</button>
     </div>
    </div>
</form>
</div>
{% endblock %}

blog/templates/createPost.html
{% extends 'base.html' %}

{% block content %}
<h1 align="center">Creat a post</h1>
<form method="POST">
  <textarea name="content" id="content" class="form-control" cols="50" rows="10">  
  </textarea>
  <br>
    <div align="center">
      <button type="submit" class="btn btn-lg btn-dark">Create</button>
      </div>
</form>

{% endblock %}

blog/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form action="/edit/{{post.user.id}}" method="POST">
  <h3>Edit Your Post</h3>
  <textarea name="content" id="content" class="form-control" cols="50" rows="10">{{post.content}}</textarea>
  <br>
  <div align="center">
    <button type="submit" class="btn btn-lg btn-dark">Edit</button>
  </div>
</form>
{% endblock %}

blog/templates/home.html
{% extends "post_div.html" %}

blog/templates/login.html
{% extends 'base.html' %}

{% block section %}
<div class="container">
  <div class="d-sm-auto">
    <h1>Please <span class="text-warning"> login</span> </h1>
    <h3>To be able  to<span class="text-warning"> view profile, posts</span> and <span class="text-warning"> write more articles</span></h3>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <h1 align="center">Login Here</h1>
 <form class="col g-3" method="POST" >
  <div class="col-md-6">
  <div class="col-md-6">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control" id="email" name="email">
  </div>
  <div class="col-md-6">
    <label for="password" class="form-label">Password</label>
    <input type="password" class="form-control" id="password" name="password">
  </div>
  <div class="col-md-12 mt-2" align="center">
    <button type="submit" class="btn btn-dark">Login</button>
   </div>
  </div>
 
</form>
</div>
{% endblock %}

blog/templates/post.html
{% extends "post_div.html" %}
{% block owner%}{{username}}'s{% endblock%}
  
  {% block content %}
  <h1 align="center">{{username}}'s Post</h1>
  {% for post in posts %}
    <div class="container">
      <div class="d-md-auto justify-content-between" id="posts">
        <div class="card border-dark">
          <div class="card-header d-flex justify-content-between align-items-center">
            <a href="/post/{{post.user.username}}">{{post.user.username}}</a>
            {% if current_user.username == post.user.username %}
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-dark dropdown-toggle" data-bs-toggle="dropdown"></button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/edit/{{post.id}}">Edit</a></li>
                <li><a class="dropdown-item" href="/delete/{{post.id}}">Delete</a></li>
              </ul>
            </div>
            {% endif %}
          </div>
          <div class="card-body">
            <div class="card-text">
              {{post.content}}
            </div>
            <div class="card-footer text-muted">
              {{post.date_created}}
            </div>
          </div>
      </div>
    </div>
    <br>
    <div align="center">
      <a href="/home"
        ><button type="button" class="btn btn-dark btn-lg">Back</button></a
      >
    </div>
  {% endfor %}
  {% endblock %}

blog/templates/post_div.html
{% extends 'base.html'%}
{% block section %}
<div class="container">
  <div class="d-sm-auto">
    <h1>Welcome to <span class="text-warning">{% block owner%}{% endblock%} Blog</span> </h1>
    <h3>Read interesting articles about <span class="text-warning">wildlife</span>, 
      <span class="text-warning"> climate change</span> and <span class="text-warning">community building</span></h3>
  </div>
</div>
{% endblock %}
{% block content %}
<h1 align="center"></h1>
<h2 align="center"> Interesting Posts</h2>
{% for post in posts %}
  <div class="container">
    <div class="d-md-auto justify-content-between" id="posts">
      <div class="card border-dark">
        <div class="card-header d-flex justify-content-between align-items-center">
          <a href="/post/{{post.user.username}}">{{post.user.username}}</a>
          {% if current_user.username == post.user.username %}
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-dark dropdown-toggle" data-bs-toggle="dropdown"></button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/edit/{{post.id}}">Edit</a></li>
              <li><a class="dropdown-item" href="/delete/{{post.id}}">Delete</a></li>
            </ul>
          </div>
          {% endif %}
        </div>
        <div class="card-body">
          <div class="card-text">
            {{post.content}}
          </div>
          <div class="card-footer text-muted">
            {{post.date_created}}
          </div>
        </div>
    </div>
  </div>
  <br>
{% endfor %}
{% endblock%}

blog/templates/register.html
{% extends 'base.html' %}

{% block section %}
<div class="container">
  <div class="d-sm-auto">
    <h1>Please  register to be<span class="text-warning"> able to write posts</span> </h1>
    <h3>Write interesting articles about <span class="text-warning">wildlife</span>, 
      <span class="text-warning"> climate change</span> and <span class="text-warning">community building</span></h3>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <h1 align="center">Register Here</h1>
 <form class="col g-3" method="POST">
  <div class="col-md-6">
    <label class="visually-hidden" for="username">Username</label>
    <div class="input-group">
      <div class="input-group-text">@</div>
      <input type="text" class="form-control" id="username" placeholder="Username" name="username" required>
    </div>
  </div>
  <div class="col-md-6">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control" id="email" name="email" required>
  </div>
  <div class="col-md-6">
    <label for="password1" class="form-label">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" required>
  </div>
  <div class="col-md-6">
    <label for="password2" class="form-label"> Confirm Password</label>
    <input type="password" class="form-control" id="password2" name="password2" required>
  </div>
  <div class="col-md-12 mt-2" align="center">
    <button type="submit" class="btn btn-dark">Register</button>
   </div>
  </div>
 
</form>
</div>
{% endblock %}